### ISSUE TITLE
White spaces at EOL do not appear in BasicTiming012.xml

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc-tests#12]
The white spaces are in `span` with `xml:space="preserve"`

**Comment by palemieux** [comment]
Behaves as expected since, according to [CSS 2.1](https://www.w3.org/TR/CSS2/visuren.html#inline-formatting),

_When the total width of the inline-level boxes on a line is less than
the width of the line box containing them, their horizontal
distribution within the line box is determined by the 'text-align'
property._

In other words, `text-align` only applies if text does not overflow.

**Comment by skynavga** [comment]
On Sat, Jun 17, 2017 at 10:48 AM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> Behaves as expected since, according to CSS 2.1
> <https://www.w3.org/TR/CSS2/visuren.html#inline-formatting>,
>
>
>
>
> *When the total width of the inline-level boxes on a line is less than the
> width of the line box containing them, their horizontal distribution within
> the line box is determined by the 'text-align' property.*
>
> In other words, text-align only applies if text does not overflow.
>
But see also CSS2 text-align-last, which is implied in TTML processing even
though we don't allow the author to specify.

**Comment by palemieux** [comment]
@skynavga There is no CSS2 text-align-last. Furthermore, XSL [text-align-last](https://www.w3.org/TR/xsl/#text-align-last) does not change the semantics of text-align. but merely specifies the used value of `text-align` for the last line when `text-align=justify`.

**Comment by skynavga** [comment]
On Sun, Jul 2, 2017 at 11:07 AM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> @skynavga <https://github.com/skynavga> There is no CSS2 text-align-last.
> Furthermore, XSL text-align-last
> <https://www.w3.org/TR/xsl/#text-align-last> does not change the
> semantics of text-align. but merely specifies the used value of text-align
> for the last line when text-align=justify.
>
I meant CSS3 text-align-last
<https://drafts.csswg.org/css-text-3/#text-align-last-property>. In any
case, my point is  that some form of text align does apply to line areas
that are not completely filled (which is what I take you to mean by
"overflow").

**Comment by nigelmegitt** [comment]
> some form of text align does apply to line areas
that are not completely filled

@skynavga did you mean "that _are_ completely filled"?

**Comment by skynavga** [comment]
I mean what I said: not completely filled, which was a response to Pierre's
previous statement:

In other words, text-align only applies if text does not overflow.

**Comment by nigelmegitt** [comment]
Ok thanks, I think other people have assumed in the past that text-align applies even in overflow scenarios, by anchoring the end (or middle) of the area to a specific point. If that assumption does not apply then it would be useful to clear that ambiguity up. Apologies for bringing a probably unrelated thing into this issue - it should be raised elsewhere if it has not been already.

**Comment by skynavga** [comment]
First, let's clarify what is meant by overflow. I took PAL to mean not filling the available space, but that is not the same as overflow, where you have tts:wrapOption="noWrap" combined with tts:overflow="visible". Which situation are we discussing?

**Comment by nigelmegitt** [comment]
I'm not so sure there's a difference, in the semantics of inline alignment anyhow. Rephrasing the question as: "For lines that fill the available space, or exceed it, does the alignment behaviour defined by `tts:textAlign` apply, or is an implementation permitted to use whatever alignment it likes?" sidesteps the detail of the values of `tts:wrapOption` and `tts:overflow`.

**Comment by palemieux** [comment]
If `tts:wrapOption=noWrap` then `tts:textAlign` only applies if the width of the line is less than the width of the region, otherwise text alignment is dictated by the direction of the text.

See https://codepen.io/palemieux/pen/xrjReG

**Comment by nigelmegitt** [comment]
Thanks for that @palemieux - that's a surprising result to me, but good to know.

**Comment by skynavga** [comment]
@palemieux just to make sure we have a shared understanding, the width of a line can only be less than the width of a region (considering horizontal modes for the moment) when:

* the region has a padding or border at the start or end edges
* (TTML2 only) tts:ipd is applied to an inline block or other block area (generated by p, div, or body), and the resolved value of ipd is less than the width of the region

however, if due to ``tts:wrapOption='noWrap'``, the inline areas of a line area extend outside the line area, then text align would not apply to that line; i.e.,  if overflow does occur, then don't align

**Comment by palemieux** [comment]
> the inline areas of a line area extend outside the line area, then text align would not apply to that line; i.e., if overflow does occur, then don't align

I think this is what the codepen shows, right?

>  the width of a line can only be less than the width of a region (considering horizontal modes for the moment) when:

What do you call the part of the line whose background color is specified by backgroundColor on span?

**Comment by skynavga** [comment]
On Mon, Jul 3, 2017 at 4:33 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> the inline areas of a line area extend outside the line area, then text
> align would not apply to that line; i.e., if overflow does occur, then
> don't align
>
> I think this is what the codepen shows, right?
>
> the width of a line can only be less than the width of a region
> (considering horizontal modes for the moment) when:
>
> What do you call the part of the line whose background color is specified
> by backgroundColor on span?
>
I would call it the background color applied to (of) an inline area child
of the line area. Except for the introduction of tts:fillLineGap, there is
no TTML1 or TTML2 semantic that applies background color to an individual
line area.

**Comment by palemieux** [comment]
Ok. Why does `tts:ipd` impact the width of the line area?

Also, out of curiosity, what area does backgroundColor on `p` apply to?

**Comment by skynavga** [comment]
On Mon, Jul 3, 2017 at 5:26 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> Ok. Why does tts:ipd impact the width of the line area?
>
tts:ipd can be used to specify the inline progression dimension of block
areas generated by

   - span with tts:display='inlineBlock'
   - p
   - div
   - body

 which affects the available space that can be allocated to line area
children of these block areas

> Also, out of curiosity, what area does backgroundColor on p apply to?
>
the block area(s) generated by p; in TTML, this will be at most one block
area, since we don't have page breaks

**Comment by palemieux** [comment]
> @palemieux just to make sure we have a shared understanding

Nothing comes to mind, but I have not experimented with TTML2.
