### ISSUE TITLE
No text visible and spurious tts:extent in DisplayAlign00X

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc-tests#20]
The initial value of `tts:color` is white, which makes the text unreadable since `tts:backgroundColor="white"`, and `tts:extent="200px 170px"` is overridden by `tts:extent="100% 100%"`.

Proposal:

* set `tts:backgroundColor="black"` on the `region`
* remove `<style tts:extent="200px 170px"/>`
* replace `tts:extent="100% 100%"` with `tts:extent="200px 170px"`

**Comment by mikedo** [comment]
"green" -> "lime" on par with the other full luminance color names used.

**Comment by palemieux** [comment]
> "green" -> "lime" on par with the other full luminance color names used.

"lime" is too bright for a background if the text is "white".

Changed to "black"

**Comment by palemieux** [comment]
> replace tts:extent="100% 100%" with tts:extent="200px 170px"

`tts:extent="100% 100%"` should be kept since no `px` measures are used
