### ISSUE TITLE
Declare a v1 release

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc-tests#36]
* [ ] Post to ttwg public reflector
* [ ] Add to TTWG wiki page (at least)
* [ ] Create a v1 release tag

**Comment by palemieux** [comment]
Release tag at https://github.com/w3c/imsc-tests/releases/tag/v1.0.0

Wiki updated at https://www.w3.org/wiki/TimedText

Announcement posted to TTWG reflector
