### ISSUE TITLE
Test files fail validation

### ISSUE THREAD

**Issue by stevn** [w3c/imsc-tests#42]
Using the [Timed Text Toolkit](https://github.com/skynav/ttt), the following files don't pass the TTXV semantic validation:

- [TimeExpressions001](https://github.com/w3c/imsc-tests/blob/master/imsc1/ttml/timing/TimeExpressions001.ttml)
- [ZIndex001](https://github.com/w3c/imsc-tests/blob/master/imsc1/ttml/zIndex/ZIndex001.ttml)

# TimeExpressions001 

Timed Text Transforming Verifier (TTXV) [1.0.0dev] Copyright 2013-16 Skynav, Inc.
[I]:Loaded configuration from 'jar:file:/C:/automated_testing/executables/ttt/ttt-ttxv-all-3.0-SNAPSHOT.jar!/com/skynav/ttx/app/config.xml'.
[I]:Configuration is empty.
[I]:Verifying resource presence and encoding phase 1...
[I]:Resource encoding sniffed as UTF-8.
[I]:Resource length 930 bytes, decoded as 930 Java characters (char).
[I]:Verifying XML well-formedness phase 2...
[I]:Verifying XSD validity phase 3...
[D]:Searching for built-in schema at com/skynav/ttv/xsd/ttml1/ttml1.xsd...
[D]:Found resource match at {jar:file:/C:/automated_testing/executables/ttt/ttt-ttxv-all-3.0-SNAPSHOT.jar!/com/skynav/ttv/xsd/ttml1/ttml1.xsd}.
[D]:Searching for built-in schema at com/skynav/ttv/xsd/smpte/2010/smpte-tt.xsd...
[D]:Found resource match at {jar:file:/C:/automated_testing/executables/ttt/ttt-ttxv-all-3.0-SNAPSHOT.jar!/com/skynav/ttv/xsd/smpte/2010/smpte-tt.xsd}.
[D]:Searching for built-in schema at com/skynav/ttv/xsd/imsc1/imsc1.xsd...
[D]:Found resource match at {jar:file:/C:/automated_testing/executables/ttt/ttt-ttxv-all-3.0-SNAPSHOT.jar!/com/skynav/ttv/xsd/imsc1/imsc1.xsd}.
[D]:Loading (and validating) schema components at {[jar:file:/C:/automated_testing/executables/ttt/ttt-ttxv-all-3.0-SNAPSHOT.jar!/com/skynav/ttv/xsd/ttml1/ttml1.xsd, jar:file:/C:/automated_testing/executables/ttt/ttt-ttxv-all-3.0-SNAPSHOT.jar!/com/skynav/ttv/xsd/smpte/2010/smpte-tt.xsd, jar:file:/C:/automated_testing/executables/ttt/ttt-ttxv-all-3.0-SNAPSHOT.jar!/com/skynav/ttv/xsd/imsc1/imsc1.xsd]}...
[I]:Verifying semantics phase 4 using 'imsc1' model...
[I]:[20,27]:Bad <timeExpression>, frames '100' must be less than frame rate 24.
**[E]:[20,27]:Invalid dur value '100:00:00:100'.**
[W]:[10,18]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[W]:[11,18]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[W]:[12,18]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[W]:[13,17]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[W]:[14,18]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[W]:[15,22]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[W]:[16,26]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[W]:[17,27]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[W]:[18,25]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[W]:[19,25]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[I]:Verification Failed, with 1 error, and with 10 warnings.
[I]:Failed 1 resource.

# ZIndex001

Timed Text Transforming Verifier (TTXV) [1.0.0dev] Copyright 2013-16 Skynav, Inc.
[I]:Loaded configuration from 'jar:file:/C:/automated_testing/executables/ttt/ttt-ttxv-all-3.0-SNAPSHOT.jar!/com/skynav/ttx/app/config.xml'.
[I]:Configuration is empty.
[I]:Verifying resource presence and encoding phase 1...
[I]:Resource encoding sniffed as UTF-8.
[I]:Resource length 1,513 bytes, decoded as 1,513 Java characters (char).
[I]:Verifying XML well-formedness phase 2...
[I]:Verifying XSD validity phase 3...
[D]:Searching for built-in schema at com/skynav/ttv/xsd/ttml1/ttml1.xsd...
[D]:Found resource match at {jar:file:/C:/automated_testing/executables/ttt/ttt-ttxv-all-3.0-SNAPSHOT.jar!/com/skynav/ttv/xsd/ttml1/ttml1.xsd}.
[D]:Searching for built-in schema at com/skynav/ttv/xsd/smpte/2010/smpte-tt.xsd...
[D]:Found resource match at {jar:file:/C:/automated_testing/executables/ttt/ttt-ttxv-all-3.0-SNAPSHOT.jar!/com/skynav/ttv/xsd/smpte/2010/smpte-tt.xsd}.
[D]:Searching for built-in schema at com/skynav/ttv/xsd/imsc1/imsc1.xsd...
[D]:Found resource match at {jar:file:/C:/automated_testing/executables/ttt/ttt-ttxv-all-3.0-SNAPSHOT.jar!/com/skynav/ttv/xsd/imsc1/imsc1.xsd}.
[D]:Loading (and validating) schema components at {[jar:file:/C:/automated_testing/executables/ttt/ttt-ttxv-all-3.0-SNAPSHOT.jar!/com/skynav/ttv/xsd/ttml1/ttml1.xsd, jar:file:/C:/automated_testing/executables/ttt/ttt-ttxv-all-3.0-SNAPSHOT.jar!/com/skynav/ttv/xsd/smpte/2010/smpte-tt.xsd, jar:file:/C:/automated_testing/executables/ttt/ttt-ttxv-all-3.0-SNAPSHOT.jar!/com/skynav/ttv/xsd/imsc1/imsc1.xsd]}...
[I]:Verifying semantics phase 4 using 'imsc1' model...
**[E]:[15,106]:Style attribute '{http://www.w3.org/ns/ttml#styling}extent' required on '{http://www.w3.org/ns/ttml}region'.
[E]:[16,102]:Style attribute '{http://www.w3.org/ns/ttml#styling}extent' required on '{http://www.w3.org/ns/ttml}region'.
[E]:[17,103]:Style attribute '{http://www.w3.org/ns/ttml#styling}extent' required on '{http://www.w3.org/ns/ttml}region'.
[E]:[18,107]:Style attribute '{http://www.w3.org/ns/ttml#styling}extent' required on '{http://www.w3.org/ns/ttml}region'.
[E]:[19,107]:Style attribute '{http://www.w3.org/ns/ttml#styling}extent' required on '{http://www.w3.org/ns/ttml}region'.
[E]:[20,107]:Style attribute '{http://www.w3.org/ns/ttml#styling}extent' required on '{http://www.w3.org/ns/ttml}region'.**
[W]:[25,28]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[W]:[26,28]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[W]:[27,28]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[W]:[28,28]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[W]:[29,28]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[W]:[30,28]:Timeable content '{http://www.w3.org/ns/ttml}p' is missing explicit @begin and/or @end on self or ancestor.
[I]:Verification Failed, with 6 errors, and with 6 warnings.
[I]:Failed 1 resource.

**Comment by stevn** [comment]
Found another invalid file.

- [BeginEnd002.ttml](https://github.com/w3c/imsc-tests/blob/master/imsc1/ttml/timing/BeginEnd002.ttml)

[E]:[12,54]:Style attribute '{http://www.w3.org/ns/ttml#styling}extent' required on '{http://www.w3.org/ns/ttml}region'.

**Comment by palemieux** [comment]
@stevn See https://github.com/w3c/imsc-tests/pull/43/commits/2f497ddf5deabfdf11f9e67b691f51166812b01a
