### ISSUE TITLE
Check output images are clearly described

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc-tests#66]
Following conversation in TTWG meeting today, need to verify that conventions used in output images of tests are clearly documented and appropriate caveats are present.

**Comment by palemieux** [comment]
See documentation at https://github.com/w3c/imsc-tests/blob/master/imsc1/README.md

**Comment by nigelmegitt** [comment]
Thank you. I think we need small edits to handle what we will do in the two cases:

1. The test document specifies a `tts:extent` that is bigger or smaller but the same aspect ratio
2. The test document specifies a different aspect ratio.
